[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/git-open"]
    type = "archive"
    url = "https://github.com/paulirish/git-open/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/you-should-use"]
    type = "archive"
    url = "https://github.com/MichaelAquilina/zsh-you-should-use/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"